### PR TITLE
Fix: added error catch in github retreiver service

### LINKED ISSUE #302: A New 500 Error on the modules page
```
2015-01-11T11:29:20-07:00 ERR (3): Exception:n1: Not FoundnTrace:n#0 [internal function]: EdpGithub\Listener\Error->postSend(Object(Zend\EventManager\Event))
#1 /var/www/modules/vendor/zendframework/zendframework/library/Zend/EventManager/EventManager.php(468): call_user_func(Array, Object(Zend\EventManager\Event))
#2 /var/www/modules/vendor/zendframework/zendframework/library/Zend/EventManager/EventManager.php(207): Zend\EventManager\EventManager->triggerListeners('post.send', Object(Zend\EventManager\Event), NULL)
#3 /var/www/modules/vendor/evandotpro/edp-github/src/EdpGithub/Http/Client.php(135): Zend\EventManager\EventManager->trigger('post.send', Object(Zend\Http\Response))
#4 /var/www/modules/vendor/evandotpro/edp-github/src/EdpGithub/Http/Client.php(63): EdpGithub\Http\Client->request('repos/neoglez/B...', Array, 'GET', Array)
#5 /var/www/modules/vendor/evandotpro/edp-github/src/EdpGithub/Api/AbstractApi.php(22): EdpGithub\Http\Client->get('repos/neoglez/B...', Array, Array)
#6 /var/www/modules/vendor/evandotpro/edp-github/src/EdpGithub/Api/Repos.php(35): EdpGithub\Api\AbstractApi->get('repos/neoglez/B...')
#7 /var/www/modules/module/Application/src/Application/Service/RepositoryRetriever.php(73): EdpGithub\Api\Repos->content('neoglez', 'BatchManager', 'LICENSE')
#8 /var/www/modules/module/Application/src/Application/Service/RepositoryRetriever.php(55): Application\Service\RepositoryRetriever->getRepositoryFileMetadata('neoglez', 'BatchManager', 'LICENSE')
#9 /var/www/modules/module/ZfModule/src/ZfModule/Controller/IndexController.php(61): Application\Service\RepositoryRetriever->getRepositoryFileContent('neoglez', 'BatchManager', 'LICENSE')
#10 /var/www/modules/vendor/zendframework/zendframework/library/Zend/Mvc/Controller/AbstractActionController.php(83): ZfModule\Controller\IndexController->viewAction()
#11 [internal function]: Zend\Mvc\Controller\AbstractActionController->onDispatch(Object(Zend\Mvc\MvcEvent))
#12 /var/www/modules/vendor/zendframework/zendframework/library/Zend/EventManager/EventManager.php(468): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
#13 /var/www/modules/vendor/zendframework/zendframework/library/Zend/EventManager/EventManager.php(207): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#14 /var/www/modules/vendor/zendframework/zendframework/library/Zend/Mvc/Controller/AbstractController.php(116): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#15 /var/www/modules/vendor/zendframework/zendframework/library/Zend/Mvc/DispatchListener.php(113): Zend\Mvc\Controller\AbstractController->dispatch(Object(Zend\Http\PhpEnvironment\Request), Object(Zend\Http\PhpEnvironment\Response))
#16 [internal function]: Zend\Mvc\DispatchListener->onDispatch(Object(Zend\Mvc\MvcEvent))
#17 /var/www/modules/vendor/zendframework/zendframework/library/Zend/EventManager/EventManager.php(468): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
#18 /var/www/modules/vendor/zendframework/zendframework/library/Zend/EventManager/EventManager.php(207): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#19 /var/www/modules/vendor/zendframework/zendframework/library/Zend/Mvc/Application.php(313): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#20 /var/www/modules/public/index.php(17): Zend\Mvc\Application->run()
#21 {main}
```

Any ideas?

### PR DESCRIPTION
**Pull request by ins0**
re-added try catch to github retreiver to reflect github exceptions not to the consumer.

this fixes #302 

/cc @GeeH

### CODE REVIEW

File: module/Application/src/Application/Service/RepositoryRetriever.php [hunk 1]
```diff
@@ -23,39 +23,50 @@ public function __construct(Client $githubClient)
...
      * @return mixed
      */
     public function getUserRepositoryMetadata($user, $module)
     {
-        return json_decode($this->githubClient->api('repos')->show($user, $module));
+        try {
+            $apiResponse = $this->githubClient->api('repos')->show($user, $module);
+            return json_decode($apiResponse);
+        } catch (RuntimeException $e) {
+            return false;
```
Comment (localheinz) [inline module/Application/src/Application/Service/RepositoryRetriever.php]: I think `null` would be a more appropriate return value in case nothing was found, no?

Think of the return values of 

```php
/* @var Doctrine\ORM\EntityRepository $entityRepository*/ 
$entityRepository->findOneBy([
    'user' => $user,
    'module' => $module,
]);
```

**Comment by localheinz** [comment]
@ins0 

Overall looks good to me, please note https://github.com/zendframework/modules.zendframework.com/pull/304#discussion_r23132351.

@GeeH 

Any news on whether it's safe to merge PRs now?

**Comment by GeeH** [comment]
I’d like to wait until we’ve met next week. Currently we aren’t even running on master as it’s broken, so I’d prefer to flip back to master when you, I, and @ocramius are around a table so we can get everything to a known state if that’s ok with you guys?




On 18 January 2015 at 10:40:46, Andreas Möller (notifications@github.com) wrote:

@ins0

Overall looks good to me, please note #304 (comment).

@GeeH

Any news on whether it's safe to merge PRs now?

**Comment by localheinz** [comment]
@GeeH 

Looking forward to talk to you there!

**Comment by ins0** [comment]
@GeeH totally agree with that

File: module/Application/src/Application/Service/RepositoryRetriever.php (hunk 1 above)
Comment (ins0) [inline module/Application/src/Application/Service/RepositoryRetriever.php]: don't know was thinking ``false`` would be a better return value in case of something went wrong

Comment (ins0) [inline module/Application/src/Application/Service/RepositoryRetriever.php]: ping @localheinz
