### PR TITLE
Fix/Blocker: adding new modules

### LINKED ISSUE #337: Adding modules currently unavailable
because of the module hydrathor and the changes from commit https://github.com/zendframework/modules.zendframework.com/commit/c29ba795a483a42bd681cf6f61e5e08604bd8c29#diff-a97d55a60a4fa4a22114687d482b38e4R88 

adding modules result in an hard error ``DateTime to string`` failure.

### PR DESCRIPTION
**Pull request by ins0**
fixes #337

### CODE REVIEW

File: module/ZfModule/test/ZfModuleTest/Mapper/ModuleHydratorTest.php [hunk 1]
```diff
@@ -0,0 +1,66 @@
...
+        $moduleEntity->setId(999);
+        $moduleEntity->setName('fooName');
+        $moduleEntity->setOwner('fooOwner');
+        $moduleEntity->setPhotoUrl('fooPhotoUrl');
+        $moduleEntity->setUrl('fooUrl');
+
+        $hydrator = new ModuleHydrator();
+        $extractedModuleArray = $hydrator->extract($moduleEntity);
+
+        $this->assertEquals([
```
Comment (localheinz) [inline module/ZfModule/test/ZfModuleTest/Mapper/ModuleHydratorTest.php]: Can be `assertSame()`.

Comment (ins0) [inline module/ZfModule/test/ZfModuleTest/Mapper/ModuleHydratorTest.php]: :+1:

**Comment by localheinz** [comment]
Thank you, @ins0!
